apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: acss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acss
  template:
    metadata:
      labels:
        app: acss
    spec:      
      containers:
      - image: nebulaepyxis/acss.backend.acss:0.0.24
        name: acss
        volumeMounts:
        - name: google-application-credentials
          mountPath: "/etc/GOOGLE_APPLICATION_CREDENTIALS"
          readOnly: true
        resources:
          requests:
            cpu: "50m"
        env:     
        # EVENT STORE CONFIG 
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/GOOGLE_APPLICATION_CREDENTIALS/gcloud-service-key.json  
        - name: EVENT_STORE_BROKER_TYPE
          value: PUBSUB
        - name: EVENT_STORE_BROKER_EVENTS_TOPIC
          value: events
        - name: EVENT_STORE_STORE_TYPE
          value: MONGO
        - name: EVENT_STORE_STORE_URL
          value: mongodb://dbevents-0.dbevents:27017,dbevents-1.dbevents:27017,dbevents-2.dbevents:27017/test?replicaSet=rs0
        - name: EVENT_STORE_STORE_AGGREGATES_DB_NAME
          value: Aggregates
        - name: EVENT_STORE_STORE_EVENTSTORE_DB_NAME
          value: EventStore
        # INTERNAL MONGO DB CONFIG
        - name: MONGODB_URL
          #value: mongodb://acss-mongo:27017
          value: mongodb://dbacss-0.dbacss:27017,dbacss-1.dbacss:27017,dbacss-2.dbacss:27017?replicaSet=rs0
        - name: MONGODB_DB_NAME
          value: acss
        # JWT CONFIG        
        - name: JWT_PUBLIC_KEY
          value: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsQBquKLlhsh1IObDD+KP45iBjelCjiF4mxLEqFkwHpGBZZckjQRPeXCc/z/nhJd47VnmyFiRFNGifpIraneLJYz1XrJ6B1fqGyfLf4mFErIffk4lQpCVUeaW/QyMFdwHN2jhe3S7yWx3gaD3ZKOX7egqZhD5gTEaYldhJX26kmJJHvuuG8t/etjxeNLy0GhLi2E1WhP6M9NGtVKS/02P16CJPr0SFQVXOUdgi5kQUS74rHB/CzEjQNziO2v2BnZVDMbKckSpzWl/zcu388/81hIlLvYpO+NtseioIQYB9sHBoaEs2cKwNEUEGKzcDezfR8fdSoGJ2wYQBnhQTMH0ewIDAQAB\n-----END PUBLIC KEY-----
        # API - GATEWAY CONFIG
        - name: GATEWAY_REPLIES_TOPIC_SUBSCRIPTION
          value: emi-gateway-replies-topic-mbe-acss
        - name: REPLY_TIMEOUT
          value: '2000'
        - name: BROKER_TYPE
          value: PUBSUB
        # Microservice config
        - name: BALANCE_ADJUSTMENT_BUSINESS_ID
          value: '04b2f922-2caa-418f-a815-2cf90e1e096d'
        - name: BUSINESS_PLATFORM_ID
          value: '07968e76-90fe-45ba-9691-2bc299f563b9'
        # RESET LOCK INITIALIZE BACKED
        - name: LOCKVERSION
          value: "0.0.1"        
        
      volumes:
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials
      